### ISSUE TITLE
Task fails when using threaded comments and comment thread has already been resolved

### ISSUE THREAD

**Issue by imdex-brett-debeer** [pulumi/pulumi-az-pipelines-task#134]
**Describe the bug**
Task fails when using threaded comments and comment thread has already been resolved.
Error message is produced is below.

`##[error]TypeError: Cannot read property '$value' of undefined`

**To Reproduce**
1. Create a pipeline that uses the task to preview changes with threaded PR comments
2. Create a PR
3. Run pipeline
4. Resolve comments
5. Run pipeline
6. See error

**Expected behavior**
Pipeline task should create a new comment is previous comment has been resolved.

**Additional context**
Issue does not occur when using threaded PR comments.

Error is likely due to `source` being undefined on line 198 of [buildAndReleaseTask/prComment.ts](https://github.com/pulumi/pulumi-az-pipelines-task/blob/v1.1.2/buildAndReleaseTask/prComment.ts#L198)

**Comment by Frassle** [comment]
> Error is likely due to source being undefined on line 198 of 

Looks like it. Probably ok for the filter to just check if that's undef and filter out in that case.

**Comment by RobbieMcKinstry** [comment]
^Yes. We've encountered similar errors in the GitHub Action.

**Comment by aureq** [comment]
@Frassle Have we been able to progress on this since the error may have been identified?

**Comment by Frassle** [comment]
Not yet, mostly just been a case of no one having time to pick up anything from this codebase.

**Comment by ericrudder** [comment]
Reported by some other customers on SLO Dash
