### ISSUE TITLE
Make it possible to support Azure remote backend (and possibly others) 

### ISSUE THREAD

**Issue by tronelius** [pulumi/pulumi-az-pipelines-task#27]
I would like to have the Azure Devops extension to support Azure Storage as backend for state. Currently it seems like the extension is doing a "pulumi login" and expected an access token as an environmentvariable. Perhaps a good idea would to have alternative environmentvariables that could alter the behaviour to do an "pulumi login -c azblob://xxxyyyzzz" and then expect the usual 2 AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables. 

Since this is an azure devops task, it seems logical to support azure storage first.

**Comment by praneetloke** [comment]
This was completed originally with #28, but later the full support for allowing to pass login args was added with #30. The login args can be used to pass the `-c` flag to the `pulumi login` command, which will allow a user to use any of the [supported backends](https://www.pulumi.com/docs/intro/concepts/state/#logging-in).
