### ISSUE TITLE
Variable expansion does not appear to work for the "stack" field

### ISSUE THREAD

**Issue by joshsten** [pulumi/pulumi-az-pipelines-task#39]
![image](https://user-images.githubusercontent.com/218617/73987367-c3fca500-4905-11ea-900c-8f311eafec0e.png)

I would expect this to pass the value of the variable down to the pulumi command as other fields other do, but for some reason in this case it passes the variable as is literally.

This is the yaml screenshot above, but the UI based tasks have the same result.

**Comment by praneetloke** [comment]
If I understand correctly, from your screenshot, `$env:pullRequestShortName` contains the name of yet another variable that actually has the value of the stack, correct?

**Comment by joshsten** [comment]
That's correct! 

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

> If I understand correctly, from your screenshot, `$env:pullRequestShortName` contains the name of yet another variable that actually has the value of the stack, correct?

**Comment by praneetloke** [comment]
I just did a quick test and the following worked for me. I defined an outer variable with the value of `$(inner)`, which holds the actual value I need:

<img width="554" alt="Screen Shot 2020-02-07 at 13 33 01" src="https://user-images.githubusercontent.com/1466314/74067594-7e47e700-49ae-11ea-81e8-43cbeebc019c.png">

<img width="184" alt="Screen Shot 2020-02-07 at 13 33 08" src="https://user-images.githubusercontent.com/1466314/74067603-81db6e00-49ae-11ea-9ab8-b5d98e6df8fd.png">

However, when my outer variable's value itself is _not_ an expression, it doesn't work. For example, this doesn't work for me:
<img width="427" alt="Screen Shot 2020-02-07 at 13 33 24" src="https://user-images.githubusercontent.com/1466314/74067608-843dc800-49ae-11ea-843d-a710ffe030fc.png">

<img width="163" alt="Screen Shot 2020-02-07 at 13 33 38" src="https://user-images.githubusercontent.com/1466314/74067612-86078b80-49ae-11ea-8742-ef8191e76f4c.png">

Maybe the value of `$env:pullRequestShortName` in your case needs to be something `$(anotherVar)` and then your `stackName` input for the Pulumi task would just be: `$(env:pullRequestShortName)`? Can you please try that and see if that works? Also I am not sure if variable expansion would work with dynamically set variables; I haven't tried it myself and don't know if it does?

**Comment by joshsten** [comment]
That worked! I actually didn't need the env:

Sorry about taking your time. It appears it was my misusage. Thank you for the quick response.

**Comment by praneetloke** [comment]
Glad you were able to resolve it!
