### ISSUE TITLE
Get Output variables

### ISSUE THREAD

**Issue by sathya177** [pulumi/pulumi-az-pipelines-task#45]
In my Pulumi script - I'm exporting few variables/json
Is there anyway i can bring it in Output variables of Azure Pipeline task
Please share your comments.

**Comment by leezen** [comment]
You can execute `pulumi stack output` to get the value of those outputs

**Comment by sathya177** [comment]
I would like to set that output to release task variable to get that in other tasks or other stage

**Comment by leezen** [comment]
There's an example of doing exactly that with `pulumi stack output` in https://www.pulumi.com/docs/guides/continuous-delivery/azure-devops/#sample-azure-pipelines-yml

I'm going to close this issue for now, but please feel free to re-open if that doesn't answer your question.
