### ISSUE TITLE
Use build agent tool cache

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi-az-pipelines-task#59]
Currently for self-hosted agents, most pipeline tasks that use an application store the binary in the tool cache. This can then be referenced without downloading it again from source for future job runs.

It looks like the Pulumi task does check to see if the Pulumi CLI exists in the tool cache [here](https://github.com/pulumi/pulumi-az-pipelines-task/blob/9812236305db0bc0d63128a83bd3a53223bd591b/buildAndReleaseTask/index.ts#L36). However there is no logic in the installer to add the tool to the cache.

It would be good to add this logic to the [installer](https://github.com/pulumi/pulumi-az-pipelines-task/blob/master/buildAndReleaseTask/installers/pulumi.ts) to use the `cacheDir` function in the `azure-pipelines-tool-lib` SDK after downloading.

**Comment by praneetloke** [comment]
@JasonWhall apologies for the delay in getting this one published in a release but version 1.0.9 is now published that has a fix for this.
