### ISSUE TITLE
Support for pulumi refresh command

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-az-pipelines-task#71]
**Describe the solution you'd like**
Would be nice, when the plugin is supporting the `pulumi refresh`command

**Comment by praneetloke** [comment]
@dirien you should be able to type any supported command in the pick list box, if it is not already available for selection. The pick list is [editable](https://github.com/pulumi/pulumi-az-pipelines-task/blob/master/buildAndReleaseTask/task.json#L44). If you are configuring the pipeline directly in yaml, you just need to pass the value to the `cmd` input param. Did you encounter an error while trying to use the `refresh` command? If you did, could you please provide more details on what the error was?

**Comment by dirien** [comment]
hi,

from the ui i see that refresh ist not available and it shows a warning in the editor:

![image](https://user-images.githubusercontent.com/38325136/119041774-55870d80-b9b7-11eb-9878-1f503be8f2d5.png)
![image](https://user-images.githubusercontent.com/38325136/119041792-57e96780-b9b7-11eb-92fe-efc271512e25.png)

But as you wrote, when i "hardcode" it works.

So i created a PR https://github.com/pulumi/pulumi-az-pipelines-task/pull/72 to add the missing refresh to the options box. Pleae give me feedack, if somthing is not as expected in the PR. I will changei it.

**Comment by praneetloke** [comment]
@dirien the warning should be ok to ignore. The picklist options were intentionally made editable for reasons like this when a command is missing in the list to select from. Your PR looks good to me. Thank you for submitting it!

**Comment by praneetloke** [comment]
Once again, thank you for submitting the PR! The change is available with [v1.0.12](https://github.com/pulumi/pulumi-az-pipelines-task/releases/tag/v1.0.12). Your build agent should automatically pick-up the new task extension version. It might take a few minutes for it to detect the new version availability.
