### ISSUE TITLE
Migrate the task to use Node10 execution handler

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi-az-pipelines-task#84]
**Describe the bug**

In Azure DevOps, when using this task, a warning now appears:

`##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

If this is not the correct place to report, please let me know where to do so.

**To Reproduce**

Use this task in an Azure DevOps pipeline

**Expected behavior**

No warning.

**Comment by praneetloke** [comment]
Version 1.0.14 of the task extension was just released and will no longer produce this warning. Az Pipelines build agents will automatically pick up the new task extension version in sometime.

**Comment by jdudleyie** [comment]
Thanks
